services:
    web24:
        build:
            context: .
        ports:
            - 8000:8000
        volumes:
            - './:/var/www'
        networks:
            - web24
    mysql:
        image: 'mysql:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'web24-mysql:/var/lib/mysql'
        networks:
            - web24
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

networks:
    web24:
        driver: bridge
volumes:
    web24-mysql:
        driver: local

